"use client";

import { Copy, Eye, Filter, MoreHorizontal, Pencil, Search, Trash2 } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useDeferredValue, useMemo, useState, useTransition } from "react";
import { deletePost, duplicatePost, togglePostPublished } from "@/app/actions/blog";

type Translation = { language: string; title: string; slug: string; published: boolean };
export type DashboardPost = { id: string; title: string; published: boolean; featured: boolean; coverImage: string | null; category: string | null; updatedAt: string; translations: Translation[] };
const languageLabel: Record<string, string> = { fa: "فارسی", en: "English", ar: "العربية" };

export default function DashboardPostsTable({ posts, access }: { posts: DashboardPost[]; access: { write: boolean; publish: boolean; delete: boolean } }) {
  const router = useRouter();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [language, setLanguage] = useState("all"); const [openMenu, setOpenMenu] = useState<string | null>(null); const [error, setError] = useState("");
  const [isPending, startTransition] = useTransition(); const deferredQuery = useDeferredValue(query);
  const filteredPosts = useMemo(() => { const normalized = deferredQuery.trim().toLocaleLowerCase("fa"); return posts.filter((post) => (!normalized || `${post.title} ${post.translations.map((item) => item.title).join(" ")}`.toLocaleLowerCase("fa").includes(normalized)) && (status === "all" || (status === "published" ? post.published : !post.published)) && (language === "all" || post.translations.some((item) => item.language === language))); }, [deferredQuery, language, posts, status]);
  function runAction(action: () => Promise<unknown>) { setOpenMenu(null); setError(""); startTransition(async () => { try { await action(); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "عملیات انجام نشد."); } }); }

  return <section className={`posts-workspace ${isPending ? "is-updating" : ""}`}>
    <div className="posts-toolbar"><label className="search-field"><Search size={19} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="جست‌وجو در عنوان هر سه زبان…" /></label><div className="filter-group"><span className="filter-label"><Filter size={17} /> فیلتر</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="published">منتشرشده</option><option value="draft">پیش‌نویس</option></select><select value={language} onChange={(e) => setLanguage(e.target.value)}><option value="all">همه زبان‌ها</option><option value="fa">فارسی</option><option value="en">English</option><option value="ar">العربية</option></select></div></div>
    {error ? <div className="table-action-error">{error}</div> : null}
    {filteredPosts.length ? <div className="table-scroll"><table className="admin-table"><thead><tr><th>نوشته</th><th>ترجمه‌ها</th><th>وضعیت مشترک</th><th>به‌روزرسانی</th><th><span className="sr-only">عملیات</span></th></tr></thead><tbody>{filteredPosts.map((post) => {
      const view = post.translations.find((item) => item.language === "fa" && item.published) || post.translations.find((item) => item.published);
      return <tr key={post.id}><td><div className="post-title-cell">{post.coverImage ? <Image src={post.coverImage} alt="" width={44} height={44} unoptimized /> : <span className="post-thumb-placeholder">N</span>}<div><Link href={`/admin/dashboard/edit/${post.id}`}>{post.title}</Link><span>{post.category || "بدون دسته‌بندی"}{post.featured ? " · ویژه" : ""}</span></div></div></td><td><div className="group-language-badges">{["fa", "en", "ar"].map((lang) => { const translation = post.translations.find((item) => item.language === lang); return <span key={lang} className={`group-language-badge lang-${lang} ${translation ? "complete" : "missing"}`} title={translation ? `${languageLabel[lang]} کامل است` : `${languageLabel[lang]} تکمیل نشده`}>{lang.toUpperCase()}</span>; })}</div></td><td>{access.publish ? <button className={`status-badge ${post.published ? "published" : "draft"}`} type="button" onClick={() => runAction(() => togglePostPublished(post.id))}><span />{post.published ? "منتشرشده" : "پیش‌نویس"}</button> : <span className={`status-badge ${post.published ? "published" : "draft"}`}><span />{post.published ? "منتشرشده" : "پیش‌نویس"}</span>}</td><td className="date-cell">{new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium" }).format(new Date(post.updatedAt))}</td><td><div className="row-actions">{access.write ? <Link href={`/admin/dashboard/edit/${post.id}`} className="table-icon-button" title="ویرایش"><Pencil size={17} /></Link> : null}{view ? <a href={`/${view.language}/blog/${view.slug}`} target="_blank" rel="noreferrer" className="table-icon-button" title="مشاهده"><Eye size={18} /></a> : null}{access.write || access.delete ? <div className="row-menu-wrap"><button className="table-icon-button" type="button" onClick={() => setOpenMenu(openMenu === post.id ? null : post.id)}><MoreHorizontal size={19} /></button>{openMenu === post.id ? <div className="row-menu">{access.write ? <button type="button" onClick={() => runAction(() => duplicatePost(post.id))}><Copy size={16} /> ساخت کپی سه‌زبانه</button> : null}{access.delete ? <button type="button" className="danger-text" onClick={() => { if (window.confirm(`نوشته «${post.title}» و تمام ترجمه‌های آن حذف شود؟`)) runAction(() => deletePost(post.id)); }}><Trash2 size={16} /> حذف هر سه ترجمه</button> : null}</div> : null}</div> : null}</div></td></tr>;
    })}</tbody></table></div> : <div className="empty-state"><div className="empty-state-mark">N</div><h3>{posts.length ? "نوشته‌ای با این فیلتر پیدا نشد" : "اولین نوشته سه‌زبانه را بسازید"}</h3><p>{posts.length ? "فیلترها یا عبارت جست‌وجو را تغییر دهید." : "فارسی، انگلیسی و عربی را در یک فرم کامل کنید."}</p>{!posts.length && access.write ? <Link href="/admin/dashboard/new" className="admin-button compact">ساخت نوشته جدید</Link> : null}</div>}
    <footer className="table-footer"><span>نمایش {filteredPosts.length.toLocaleString("fa-IR")} نوشته از {posts.length.toLocaleString("fa-IR")}</span></footer>
  </section>;
}
